version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: server-monitor-backend
    restart: unless-stopped
    environment:
      - PORT=2000
      # Add other environment variables your backend needs
      - DB_HOST=your_db_host
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    ports:
      - "2000:2000" # Only needed if you want direct access to the backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: server-monitor-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api
      # Add other environment variables your frontend needs
    ports:
      - "3000:3000" # Only needed if you want direct access to the frontend
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: server-monitor-nginx
    restart: unless-stopped
    ports:
      - "80:80" # Expose to host on port 80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
