FROM golang:1.19-alpine AS builder

WORKDIR /app
COPY . .
RUN go build -o ./bin/main ./cmd/api

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/bin/main .
EXPOSE 2000
CMD ["./main"]