services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: server-monitor-backend
    restart: unless-stopped
    environment:
      - PORT=2000
    ports:
      - "2000:2000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: server-monitor-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: server-monitor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
